Always define VL_THREADED
verilator/verilator pull request #3686
Opened 2022-10-18 12:20 UTC by kamilrakoczy

Related to: https://github.com/verilator/verilator/pull/3680

Now configure script requires that compilator have C++11 support.

Signed-off-by: Kamil Rakoczy <krakoczy@antmicro.com>

2022-10-18 12:34 UTC, gezalore commented
Does this only apply to verilator (and not the run-time library)?

2022-10-18 13:00 UTC, kamilrakoczy commented
> Does this only apply to verilator (and not the run-time library)?

Yes, it only applies to verilator.

2022-10-18 13:18 UTC, wsnyder commented
Fundamentally we need to decide are we going to always have the multithreaded support and that's the only option, and thus we remove all usages of VL_THREADED by hardcoding it.   Or we keep the ability to have single threaded builds/models, which we should start testing if we are going to maintain both.

There was two arguments for supporting both, the first was lack of C++11 and that is gone.  The second was performance; @gezalore didn't see any significant slowdown in the runtime even when single threaded, I don't think we have enough code yet with Verilator itself to make that statement, but seems likely.

Performance still makes me nervous but I can see the code maintenance argument, so can come around.

@gezalore, @kbieganski do you think we should only have multithreaded?

2022-10-18 13:56 UTC, gezalore commented
> This is required for thread-safety analysis from clang, Attributes that this check requires are behind this define. See: https://github.com/verilator/verilator/blob/master/include/verilatedos.h#L59 / https://github.com/verilator/verilator/blob/master/include/verilated.h#L167.
> 
> In #3680 I've started to using `VL_GUARDED_BY`/`VL_REQUIRES` in verilator to make sure mutex is locked when we access specific variables.

Ok, so this is just again the code sharing between verilator and the run-time, and overloading VL_THREADED to apply both to verilator internals, and the run-time, sigh... I still am not sure why this needs to be in configure as it does not depend on anything.

2022-10-18 14:02 UTC, gezalore commented
> Fundamentally we need to decide are we going to always have the multithreaded support and that's the only option, and thus we remove all usages of VL_THREADED by hardcoding it. Or we keep the ability to have single threaded builds/models, which we should start testing if we are going to maintain both.
> 
> There was two arguments for supporting both, the first was lack of C++11 and that is gone. The second was performance; @gezalore didn't see any significant slowdown in the runtime even when single threaded, I don't think we have enough code yet with Verilator itself to make that statement, but seems likely.
> 
> Performance still makes me nervous but I can see the code maintenance argument, so can come around.
> 
> @gezalore, @kbieganski do you think we should only have multithreaded?

We are conflating two things again I think:

1. Should Verilator internals always support threads: Yes, I don't think there is a reason not to (and that's why I'm confused why the define is added in configure and am still not sure it only applies to verilator internals and not the run-time, I would just -DVL_THREADED=1 in src/Makefile_obj.in if it should only apply to verilator).
2. Should the run-time lib always support threads: This is the more controversial one. As I mentioned, I have not seen any measurable slowdown myself (AFAICT we claim some locks when printing messages, but that's about it, and the locks are always uncontested in ST mode). You could also cheat and say the single threaded gains by DFG in v5 will offset anything you might loose from having threading support always available, so unlikely people would notice any "slowdown".

2022-10-18 15:22 UTC, kbieganski commented
If we can get rid of a code path and not lose any features or significant performance then I'm all for it. But hard to say without data. Perhaps we should set up some automated benchmarks that run the biggest open source designs we can run, and use that to make decisions.

The performance hit we're worried about is running multithreaded mode on one thread, right? I imagine if someone has a design big enough that they observe significant losses there, they're better off using multiple threads anyway. Are there known designs that don't partition well?

2022-10-18 21:08 UTC, wsnyder commented
Ok, I'd suggest then to change this pull request (or make a different one) which completely removes VL_THREADED, and related non-threaded code.

2022-10-18 21:23 UTC, gezalore commented
Sounds good to me.

@kbieganski:
> The performance hit we're worried about is running multithreaded mode on one thread, right?

We are worried about running an ST model (verilated with --threads 0) on an MT runtime (run-time compiled with VL_THTEADED). Regression batch job wanting to see maximum cycles per dollar are likely best run ST (though there are cases when MT is better than Amdahl), but then again with the new optimizations in v5 we give much more than we take if we make the runtl-yime always MT.

@kamilrakoczy if you rip out VL_THREADED please don't forget to update docs where it says --threads 0 means the model will not be MT safe, which will no longer be true (--threads 0 and --threads 1 will be equivalent)

2022-10-22 01:56 UTC, wsnyder requested changes
See comments earlier - we prefer to remove VL_THREADED entirely (remove ifdefs) thanks.

2022-10-24 09:59 UTC, kamilrakoczy commented
Superseded by https://github.com/verilator/verilator/pull/3703.

2022-10-24 09:59 UTC, closed without merging